/**
* @file
* @brief Automatically generated by the XML code generator to be used by XML parser.

* This header file is generated based on the XML schema.
* It contains *food_t* structure based on the data structure of XML schema.
* This structure is useful to store the extracted content from the XML data by XML parser.

* For further details refer,
* https://github.com/kiishor/xml_code_generator
* https://github.com/kiishor/miniML-Parser
*/

#ifndef food_H_INCLUDED
#define food_H_INCLUDED

#include <stdint.h>
#include <stdbool.h>

#include "parse_xml.h"

typedef struct
{
    char* name;
    float price;
    char* description;
    uint32_t calories;
}food_t;

extern const xs_element_t food_root;

#endif
