/**
* @file
* @brief Automatically generated by the XML code generator to be used by XML parser.

* This header file is generated based on the XML schema.
* It contains *shiporder_t* structure based on the data structure of XML schema.
* This structure is useful to store the extracted content from the XML data by XML parser.

* For further details refer,
* https://github.com/kiishor/xml_code_generator
* https://github.com/kiishor/miniML-Parser
*/

#ifndef shiporder_H_INCLUDED
#define shiporder_H_INCLUDED

#include <stdint.h>
#include <stdbool.h>

#include "parse_xml.h"

typedef struct
{
    char* title;
    char* note;
    uint32_t quantity;
    float price;
}item_t;

typedef struct
{
    char* name;
    char* address;
    char* city;
    char* country;
}shipto_t;

typedef struct
{
    char* orderperson;
    shipto_t shipto;
    item_t* item;
    char* orderid;
}shiporder_t;

extern const xs_element_t shiporder_root;

#endif
